### ISSUE TITLE
可以开个坑，做一个JM的去广告吗

### ISSUE THREAD

**Issue by 694185819** [AoEiuV020/HookPicACG#2]

**Comment by 694185819** [comment]
禁漫天堂

**Comment by AoEiuV020** [comment]
不了解，没用过，如果是原生技术开发的或许可以类似的做hook去广告，但我懒得开坑自己没有使用的app，
另外试了一下聚合漫画的cimoc有支持禁漫的源，cimoc我有做去广告, 
https://github.com/AoEiuV020/HookCimoc
